#!/usr/bin/env groovy
def list = ["dir1", "dir2", "dir3", "dir4", "dir4v2", "dir5", "dir5v2", "dir6", "dir7"]
def matches 
def matchesv2
def v2dir
def redir

pipeline {
    options {
        buildDiscarder(logRotator(numToKeepStr: '6'))
    }
    agent any
    stages {
        stage ('check each services'){
            steps{
                script {
                    sh 'pwd'
                    for(int i=0; i < list.size(); i++) {
                        if("${list[i]}"!="realtimev2" && "${list[i]}"!="tagmanagerv2" && "${list[i]}"!="websocketv2"){
                            matches = sh (
                                script: "git diff --name-only HEAD~1 | sort -u | awk -F/ {'print \$2,\$3'} | uniq | grep -x '${list[i]} build'", returnStatus: true
                            ) == 0
                            echo "Matches: $matches"
                            echo "Service: ${list[i]}"
                            echo "branchname: ${BRANCH_NAME}"
                            if("$matches"!="false") {
                                stage(list[i] + ' trigger'){
                                    def scan = "../${list[i]}"
                                    echo "scanning: ${scan}"
                                    // def trigger = "../${list[i]}/${BRANCH_NAME}"
                                    script {
                                        build job: "${scan}", propagate: false, wait: false
                                        sleep 10
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}